- name: Garantindo a instalação dos pre-reqs para o Docker
  ansible.builtin.apt:
    name: [ "ca-certificates", "curl", "gnupg", "lsb-release","openssl" ]
    state: present

- name: Garantindo a chave do repositório do Docker
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Garantindo a entrada do repositório do Docker no arquivo docker.list
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/debian bullseye stable
    state: present
    filename: docker

- name: Garantindo a instalação do Docker
  ansible.builtin.apt:
    name: [ "docker-ce", "docker-ce-cli", "containerd.io" ]
    state: present
    update_cache: yes

- name: Garantindo que o usuario do linux seja adicionado ao grupo docker
  ansible.builtin.user:
    name: "{{ usuario_vm }}"
    groups: docker
    state: present
    append: yes
  notify: Restart Docker

- name: Garantindo a instalação do Docker-Compose
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/download/v2.12.2/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'
